server:
  port: 8083

logging:
  level:
    org.springframework.data.r2dbc: trace

spring:
  h2:
    console:
      enabled:true
  cloud:
    stream:
      bindings:
        runArtefact-in-0:
          destination: subscriber
          group: subscriber
          binder: rabbit

---
spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: rabbitmq